// Code generated by "stringer -type FanMode"; DO NOT EDIT

package thermostat

import "fmt"

const _FanMode_name = "FAN_AUTOFAN_AUTO_CIRCULATEFAN_ON"

var _FanMode_index = [...]uint8{0, 8, 26, 32}

func (i FanMode) String() string {
	if i < 0 || i >= FanMode(len(_FanMode_index)-1) {
		return fmt.Sprintf("FanMode(%d)", i)
	}
	return _FanMode_name[_FanMode_index[i]:_FanMode_index[i+1]]
}
